### ISSUE TITLE
balance_report(): Exception in function: name 'name' is not defined

### ISSUE THREAD

**Issue by 000KeyserSoze000** [pantersxx3/binancebot#2]
Hello, i have this error message: balance_report(): Exception in function: name 'name' is not defined

**Comment by pantersxx3** [comment]
Thanks for reporting the error, does it show you in which line number the error appears? check the log file for more details

**Comment by 000KeyserSoze000** [comment]
hello, BOT: balance_report(): Exception in function: name 'name' is not defined
Error on line 636

**Comment by pantersxx3** [comment]
The truth is that this variable does not exist in that function, I just made an update and improvements to the bot, please check and tell me if the error persists. Thank you so much
